spring.application.name=SpringRestAngularTest
server.port=8080
spring.main.banner-mode=off

# SQLite configuration
spring.datasource.url=jdbc:sqlite:customers.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Azure Entra ID - JWT Bearer Token Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/42f854a7-59d8-4513-bb97-4ff8071b21d2/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://b9af3296-edc2-462c-b417-fadc5a695865
